# Generated by Django 6.0.6 on 2026-06-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RomHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(db_index=True, max_length=32, unique=True)),
                ('file_name', models.TextField()),
                ('source', models.CharField(blank=True, max_length=120)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
